### ISSUE TITLE
ap-plugin.com 404

### ISSUE THREAD

**Issue by tym2008** [yhArcadia/ap-plugin#35]
![Screenshot_20240201_090508_com.huawei.browser.jpg](https://github.com/AiPreface/ap-plugin/assets/102407847/90b6bb23-492c-48a3-9d6d-a0c2eb00a6d9)

打不开，想看看文档都看不到

**Comment by 493Arceus** [comment]
笑死，域名都过期了，估计作者都已经弃坑了

**Comment by 493Arceus** [comment]
在这里面找：https://github.com/AiPreface/ap-plugin-website/tree/main/docs/Config
